apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  name: print-envars-greeting
spec:
  containers:
  - image: bash:latest
    name: print-env-container
    env:
    - name: GREETING
      value: "Welcome to"
    - name: COMPANY
      value: "DevOps"
    - name: GROUP 
      value: "Industries"
    command: ["/bin/sh", "-c", 'echo "$(GREETING) $(COMPANY) $(GROUP)"']
  restartPolicy: Never