- name: Disable root ssh on app-servers
  hosts: appservers
  become: yes
  tasks:
    - name: ensure PermitRootLogin set to no 
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: restart sshd
      service:
        name: sshd
        state: restarted