- name: Secure Apache Port 5004 on app servers
  hosts: appservers
  become: yes
  tasks:

    - name: Install iptables and iptables-services
      ansible.builtin.package:
        name:
          - iptables
          - iptables-services
        state: present

    - name: Allow LBR host to access Apache port
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        source: 172.16.238.14  # LBR IP
        destination_port: 6400
        jump: ACCEPT

    - name: Block all other incoming traffic on Apache port
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 6400
        jump: REJECT

    - name: Save iptables rules permanently
      community.general.iptables_state:
        state: saved
        path: /etc/sysconfig/iptables

    - name: Enable and start iptables service
      ansible.builtin.service:
        name: iptables
        state: started
        enabled: yes